spring:
  jpa:
    # JPA의 표준 속성들을 올바른 위치로 수정
    show-sql: true
    open-in-view: false
    generate-ddl: false
    # Hibernate 관련 설정은 hibernate 키 아래에 그룹화
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # 기타 Hibernate 속성은 properties.hibernate 아래에 배치
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
  datasource:
    url: jdbc:mariadb://localhost:3306/myDB
    driver-class-name: org.mariadb.jdbc.Driver
    username: poly
    password: '1234'

server:
  port: '13000'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      enabled: true
    beans:
      enabled: true
    info:
      enabled: true
    server:
        address: localhost
        port: 13001
